{% set name = "pytest-monitor" %}
{% set version = "1.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0c44dc44a2d6cdd19f84caa18fafeb1227e2b33bcbd11a2071dacd3763e1b6f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps  . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytest
    - memory_profiler >=0.58.0
    - psutil >=5.1.0
    - requests

test:
  commands:
    - pytest -h

about:
  home: https://github.com/CFMTech/pytest-monitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin to analyze your resource consumption during test phase.

  description: |
    Pytest-monitor is a pytest plugin written in pure python. It helps in 
    analyzing how your program behaves in terms of resource usage (depending on your code changes or dependencies's).
    It requires pytest, psutil and memory_profiler. Works with python 3.5+.
  doc_url: https://pytest-monitor.readthedocs.io/
  dev_url: https://github.com/CFMTech/pytest-monitor

extra:
  recipe-maintainers:
    - js-dieu
